version: '3.8'
services:
  frontend:
    build:
      context: ./smartdoc-finder-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:8080
    depends_on:
      - backend

  backend:
    build: ./smartdoc-finder-backend
    ports:
      - "8080:8080"
      - "5005:5005"  # Java Debug Port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/smartdoc
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      INDEX_PATH: "/host-documents"
      SPRING_APPLICATION_JSON: '{"embedding.service.url": "http://embedding:8000"}'
    volumes:
      - ./lucene-index:/lucene-index
      - ${USER_DATA_DIRECTORY}:/host-documents
  embedding:
    build: ./smartdoc-finder-embedding
    ports:
      - "8000:8000"
    volumes:
      - ./faiss-index:/app/index
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: smartdoc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
